# This is a basic workflow that is manually triggered

name: Klocwork demo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Run the Klocwork analysis manually'
        # Default value if no value is explicitly provided
        default: 'Manual Execution'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains the following jobs called "kwinject", "kwbuildproject" and "kwload"
  klocwork:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: msys-softverify/demosthenes
          path: demosthenes
      # Runs a single command using the runners shell
      - name: kwinject
        run: kwinject make
      - name: kwbuildproject
        run: kwbuildproject --url ${{secrets.KWSERVER}}/demosthenes_actions_demo -o tables kwinject.out -f
      - name: kwload
        run: kwadmin --url ${{secrets.KWSERVER}} load demosthenes_actions_demo tables
